name: kazoo-configs-freeswitch
base_branch: origin/master
base_core: null
template: spec.tmpl
package:
  centos7:
    name: kazoo-configs-freeswitch
    group: Productivity/Telephony
    license: MPL1.1
    build_arch: noarch
    build_requires:
      - rpm-build
    summary: Kazoo specific configuration for FreeSWITCH
    description: |
      In the Kazoo platform FreeSWITCH is utilized as simple
      media server, so this configures a minimal number of
      modules and a single SIP interface.  Kazoo will
      connect to FreeSWITCH and issue any necessary commands
      for call control or dynamic configuration. If you
      need help you can contact us via the dev mailing
      list or on IRC at #2600hz on FreeNode.
    dist: .el7.centos
    requires:
      centos7:
         sudo: {}
    source: '%{_build_tar}'
    prep: '%setup -q'
    install: |
      mkdir -p %{buildroot}/etc/kazoo
      cp -r freeswitch %{buildroot}/etc/kazoo
      cp CHANGELOG VERSION %{buildroot}/etc/kazoo/freeswitch

      mkdir -p %{buildroot}/usr/sbin
      cp -r  system/sbin/* %{buildroot}/usr/sbin
      chmod +x %{buildroot}/usr/sbin/*

      mkdir -p %{buildroot}/etc/logrotate.d
      if [ -f "system/logrotate.d/freeswitch.conf" ]; then
        if ! grep -qE '^\s+missingok' system/logrotate.d/freeswitch.conf; then
          sed -i -re 's/^[^{]+\{/&\n    missingok/' system/logrotate.d/freeswitch.conf
        fi
      fi
      cp -r  system/logrotate.d/*.conf %{buildroot}/etc/logrotate.d

      mkdir -p %{buildroot}/etc/security/limits.d
      cp -r  system/security/limits.d/*.conf %{buildroot}/etc/security/limits.d

      mkdir -p %{buildroot}/usr/lib/systemd/system
      cp system/systemd/* %{buildroot}/usr/lib/systemd/system
    post: |
        if [ -x "/usr/bin/freeswitch" ]; then
            setcap 'cap_net_bind_service,cap_sys_nice=+ep' /usr/bin/freeswitch
        fi
    files:
      doc:
        - CHANGELOG
        - VERSION
      config:
        - mode: noreplace
          path: /etc/kazoo/freeswitch
        - mode: noreplace
          path: /etc/logrotate.d/*freeswitch*
        - mode: noreplace
          path: /etc/security/limits.d/*freeswitch*
      path:
        - /usr/sbin/kazoo-freeswitch
        - /usr/lib/systemd/system/kazoo-freeswitch.service
        - /usr/lib/systemd/system/kazoo-freeswitch-logrotate.service
        - /usr/lib/systemd/system/kazoo-freeswitch-logrotate.timer
    url: 'http://www.2600hz.org'
    vendor: 2600Hz
metapackage:
  -
    name: meta-kazoo-freeswitch
    package: kazoo-configs-haproxy
    type: required
    branch: 'master'
